### PR TITLE
Updated logger reference

### PR DESCRIPTION
**Pull request by niftylettuce**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Doug-AWS** [comment]
Let me run this by the JS team and get back to you.

**Comment by wsierakowski** [comment]
That's sneaky, attempt to swap the logger module out of the blue to promote the one that the PR author created... It would be actually fair to replace the reference to a specific logger module with something generic, like, `your_logger_library`. Otherwise other authors will keep coming here to open PRs to replace `cabin` with their own libraries.

**Comment by niftylettuce** [comment]
There is nothing sneaky going on. My logger is completely open source and MIT licensed - and it itself is logger agnostic (you could have two different loggers, one for production and one for development as the PR shows).  You can even hook in your own callback function (e.g. a Slack webhook for error or fatal log levels).

**Comment by Doug-AWS** [comment]
I'm going to have to reject this as the code is correct and the explanation about using any logger is adequate.

**Pull request closed without merging**
